import { WebsiteConfig } from "@/context/BuilderContext";

export const realtorConfig: WebsiteConfig = {
    template: 'realtor',
    colors: {
        primary: '#1A2D49', // Slate 900
        secondary: '#F59E0B', // Amber 500
        text: '#0f172a', // Slate 900
        background: '#ffffff',
        accent: '#F59E0B',
    },
    content: {
        logos: {},
        text: {
            'brand.name': 'LUXE ESTATES',
            'hero.title': 'Find Your Dream \nSanctuary',
            'hero.subtitle': 'Exclusive properties for exclusive lifestyles. We help you find the perfect home that matches your vision and ambition.',
            'hero.cta': 'Explore Properties',
            'about.title': 'About Me',
            'about.description': 'I am a dedicated real estate professional with over 15 years of experience in the luxury market. My mission is to help you find not just a house, but a place where you can truly belong.',
            'about.stat.number': '15+',
            'about.stat.label': 'Years of Experience in Luxury Real Estate',
            'about.checklist1': 'Certified Luxury Home Marketing Specialist',
            'about.checklist2': 'Top 1% Producer in the Region',
            'about.checklist3': 'Expert in Negotiation and Market Analysis',
            'about.cta': 'Read Full Bio',
            'services.title': 'Our Services',
            'services.subtitle': 'Comprehensive real estate solutions tailored to your unique needs.',
            'services.description': "Whether you're buying, selling, or investing, we provide the expertise and support you need to achieve your goals.",
            'services.buying.title': 'Buying a Home',
            'services.buying.description': 'Find your perfect sanctuary with our curated property search and expert guidance through every step.',
            'services.selling.title': 'Selling Your Home',
            'services.selling.description': "Maximize your property's value with our strategic marketing, staging advice, and negotiation skills.",
            'services.market.title': 'Market Analysis',
            'services.market.description': 'Make informed decisions with our comprehensive market reports and investment insights.',
            'why.title': 'Why Choose Me',
            'why.subtitle': 'Unmatched Dedication to Your Success',
            'why.description': 'In a crowded market, experience and integrity matter. My proven track record and client-first approach ensure that your real estate journey is smooth, successful, and stress-free.',
            'why.stat1.number': '150+',
            'why.stat1.label': 'Homes Sold',
            'why.stat2.number': '$250M',
            'why.stat2.label': 'Sales Volume',
            'why.reason1.title': 'Award Winning',
            'why.reason1.description': 'Recognized excellence in luxury real estate sales.',
            'why.reason2.title': '24/7 Availability',
            'why.reason2.description': 'Always available to answer your questions and concerns.',
            'why.reason3.title': 'Vast Network',
            'why.reason3.description': 'Access to exclusive off-market listings and buyers.',
            'why.reason4.title': 'Trusted Advisor',
            'why.reason4.description': 'Honest, transparent, and ethical representation.',
            'social.title': 'Testimonials',
            'social.subtitle': 'What My Clients Say',
            'social.testimonial1.text': "We couldn't have asked for a better agent. Their knowledge of the market and negotiation skills got us our dream home under asking price!",
            'social.testimonial1.author': 'Sarah & James M.',
            'social.testimonial1.location': 'Beverly Hills, CA',
            'social.testimonial2.text': 'Professional, attentive, and incredibly hardworking. Sold our property in record time for a price we didn\'t think was possible.',
            'social.testimonial2.author': 'Robert T.',
            'social.testimonial2.location': 'Hollywood Hills, CA',
            'social.testimonial3.text': 'Guided us through every step of the process with patience and expertise. Truly went above and beyond our expectations.',
            'social.testimonial3.author': 'Emily R.',
            'social.testimonial3.location': 'Santa Monica, CA',
            'consultation.title': 'Ready to Find Your Dream Home?',
            'consultation.text': "Let's discuss your real estate goals. Schedule a free, no-obligation consultation today.",
            'consultation.cta': 'Book a Call',
            'contact.title': 'Get in Touch',
            'contact.subtitle': "Let's Start a Conversation",
            'contact.phone': '+1 (555) 123-4567',
            'contact.email': 'hello@luxeestates.com',
            'contact.address': '123 Luxury Blvd, Beverly Hills, CA 90210',
        },
        images: {
            headshot: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=2574&auto=format&fit=crop',
        },
        socialLinks: [
            { platform: 'instagram', url: 'https://instagram.com' },
            { platform: 'linkedin', url: 'https://linkedin.com' },
            { platform: 'facebook', url: 'https://facebook.com' },
        ],
    },
};
